Repository funidata/hybridilusmu, pull requests merged in 2023-07, with the labels that each got.

#79 CI: Run checks for merge groups
  .github/workflows/push_other_branches.yaml
Labels: maintenance

#80 Test to see if we don't need explicit merge_groups trigger after all
  .github/workflows/push_other_branches.yaml
Labels: maintenance

#82 Merge queue test 2
  docs/cicd_pipeline.md
Labels: maintenance

#84 Merge queue test 3
  README.md
Labels: maintenance

#86 Deploy documentation to GH Pages
  .github/workflows/release.yaml
  .github/workflows/release_docs.yaml
  .gitignore
  README.md
  docs/package-lock.json
  docs/package.json
  docs/src/.vuepress/config.ts
  docs/src/.vuepress/public/logo/favicon.png
  docs/src/.vuepress/public/logo/hybridilusmulogo1darkbg.jpg
  docs/src/.vuepress/public/logo/hybridilusmulogo1darkbgsmall.jpg
  docs/src/.vuepress/public/logo/hybridilusmulogo1whitebg.jpg
  docs/src/.vuepress/public/logo/hybridilusmulogo1whitebgsmall.jpg
  docs/src/developing.md
  docs/src/index.md
  docs/src/introduction.md
  docs/src/releases.md
  docs/src/tests.md
  docs_old/cicd_pipeline.md
  docs_old/kayttoohje.md
  docs_old/kayttoonottoohjeet.md
  docs_old/manifest.yml
  docs_old/slack-sovelluksen_perusteet.md
  docs_old/testaaminen.md
Labels: maintenance

#89 Configuration updates to enable production use
  app/.sequelizerc.js
  app/Dockerfile
  app/package-lock.json
  app/package.json
  compose.yaml
  docs/.prettierrc.yaml
  docs/src/.vuepress/config.ts
  docs/src/developing.md
  docs/src/hosting.md
  package.json
Labels: bug, maintenance

#90 GHA workflow permissions fix
  .github/workflows/release.yaml
  app/package-lock.json
  app/package.json
  package.json
Labels: bug, maintenance

#76 Feature/issue 2/multiple premises
  app/package-lock.json
  app/package.json
  app/src/actionFunctions.js
  app/src/blocks/elements/button.js
  app/src/blocks/header.js
  app/src/blocks/section.js
  app/src/controllers/db.controllers.js
  app/src/databaseService.js
  app/src/eventListeners.js
  app/src/helperFunctions.js
  app/src/home.js
  app/src/index.js
  app/src/lateRegistration.js
  app/src/middleware.js
  app/src/migrations/20230627064405-create-office.js
  app/src/migrations/20230627074343-add-office-id-to-signup-and-defaultsignup.js
  app/src/migrations/20230627091637-add-default-office-to-people.js
  app/src/migrations/20230629114921-add-default-office-and-populate.js
  app/src/migrations/20230711112437-add-office-emoji-to-offices.js
  app/src/migrations/20230717091938-add-office-reference-to-jobs.js
  app/src/migrations/20230717105644-clean-up-fkey-constraints.js
  app/src/models/defaultsignup.js
  app/src/models/job.js
  app/src/models/office.js
  app/src/models/person.js
  app/src/models/scheduledmessage.js
  app/src/models/signup.js
  app/src/responses.js
  app/src/scheduler/scheduledMessage.js
  app/src/scheduler/scheduler.js
  app/src/slashCommands.js
  app/src/ui/blocks/actions.js
  app/src/ui/blocks/context.js
  app/src/ui/blocks/divider.js
  app/src/ui/blocks/elements/button.js
  app/src/ui/blocks/elements/confirmation.js
  app/src/ui/blocks/elements/defaultSettingButton.js
  app/src/ui/blocks/elements/overflow.js
  app/src/ui/blocks/elements/selectMenu.js
  app/src/ui/blocks/elements/textInput.js
  app/src/ui/blocks/header.js
  app/src/ui/blocks/section.js
  app/src/ui/customBlocks.js
  app/src/ui/home.js
  app/src/ui/modals.js
  app/src/userCache.js
  app/src/viewListeners.js
  app/test/ui.test.js
  docs_old/manifest.yml
  package.json
Labels: feature
